#pragma once

#include <algorithm>
#include <unordered_map>
#include <SDL3/SDL.h>

struct inputState {
    bool state = false;
    bool prevState = false;
    bool pressedHandled = false;
    bool releasedHandled = false;
};

class InputManager {
private:
    bool quit = false;
    inputState keyStates[SDL_NUM_SCANCODES];
    inputState mouseStates[5];
    SDL_Point mousePosition;

public:
    InputManager();

    void PollEvents();
    bool IsQuitRequested() const;
    bool IsDown(inputState* inputStates, int key);
    bool IsUp(inputState* inputStates, int key);
    bool IsPressed(inputState* inputStates, int key);
    bool IsReleased(inputState* inputStates, int key);

    SDL_Point GetMousePosition();

    // MOUSE
    bool IsDown_LeftMouse() { return IsDown(mouseStates, SDL_BUTTON_LEFT); }
    bool IsUp_LeftMouse() { return IsUp(mouseStates, SDL_BUTTON_LEFT); }
    bool IsPressed_LeftMouse() { return IsPressed(mouseStates, SDL_BUTTON_LEFT); }
    bool IsReleased_LeftMouse() { return IsReleased(mouseStates, SDL_BUTTON_LEFT); }
    bool IsDown_RightMouse() { return IsDown(mouseStates, SDL_BUTTON_RIGHT); }
    bool IsUp_RightMouse() { return IsUp(mouseStates, SDL_BUTTON_RIGHT); }
    bool IsPressed_RightMouse() { return IsPressed(mouseStates, SDL_BUTTON_RIGHT); }
    bool IsReleased_RightMouse() { return IsReleased(mouseStates, SDL_BUTTON_RIGHT); }

    // KEYBOARD PRESSED
    bool IsPressed_A() { return IsPressed(keyStates,SDL_SCANCODE_A); }
    bool IsPressed_B() { return IsPressed(keyStates,SDL_SCANCODE_B); }
    bool IsPressed_C() { return IsPressed(keyStates,SDL_SCANCODE_C); }
    bool IsPressed_D() { return IsPressed(keyStates,SDL_SCANCODE_D); }
    bool IsPressed_E() { return IsPressed(keyStates,SDL_SCANCODE_E); }
    bool IsPressed_F() { return IsPressed(keyStates,SDL_SCANCODE_F); }
    bool IsPressed_G() { return IsPressed(keyStates,SDL_SCANCODE_G); }
    bool IsPressed_H() { return IsPressed(keyStates,SDL_SCANCODE_H); }
    bool IsPressed_I() { return IsPressed(keyStates,SDL_SCANCODE_I); }
    bool IsPressed_J() { return IsPressed(keyStates,SDL_SCANCODE_J); }
    bool IsPressed_K() { return IsPressed(keyStates,SDL_SCANCODE_K); }
    bool IsPressed_L() { return IsPressed(keyStates,SDL_SCANCODE_L); }
    bool IsPressed_M() { return IsPressed(keyStates,SDL_SCANCODE_M); }
    bool IsPressed_N() { return IsPressed(keyStates,SDL_SCANCODE_N); }
    bool IsPressed_O() { return IsPressed(keyStates,SDL_SCANCODE_O); }
    bool IsPressed_P() { return IsPressed(keyStates,SDL_SCANCODE_P); }
    bool IsPressed_Q() { return IsPressed(keyStates,SDL_SCANCODE_Q); }
    bool IsPressed_R() { return IsPressed(keyStates,SDL_SCANCODE_R); }
    bool IsPressed_S() { return IsPressed(keyStates,SDL_SCANCODE_S); }
    bool IsPressed_T() { return IsPressed(keyStates,SDL_SCANCODE_T); }
    bool IsPressed_U() { return IsPressed(keyStates,SDL_SCANCODE_U); }
    bool IsPressed_V() { return IsPressed(keyStates,SDL_SCANCODE_V); }
    bool IsPressed_W() { return IsPressed(keyStates,SDL_SCANCODE_W); }
    bool IsPressed_X() { return IsPressed(keyStates,SDL_SCANCODE_X); }
    bool IsPressed_Y() { return IsPressed(keyStates,SDL_SCANCODE_Y); }
    bool IsPressed_Z() { return IsPressed(keyStates,SDL_SCANCODE_Z); }
    bool IsPressed_1() { return IsPressed(keyStates,SDL_SCANCODE_1); }
    bool IsPressed_2() { return IsPressed(keyStates,SDL_SCANCODE_2); }
    bool IsPressed_3() { return IsPressed(keyStates,SDL_SCANCODE_3); }
    bool IsPressed_4() { return IsPressed(keyStates,SDL_SCANCODE_4); }
    bool IsPressed_5() { return IsPressed(keyStates,SDL_SCANCODE_5); }
    bool IsPressed_6() { return IsPressed(keyStates,SDL_SCANCODE_6); }
    bool IsPressed_7() { return IsPressed(keyStates,SDL_SCANCODE_7); }
    bool IsPressed_8() { return IsPressed(keyStates,SDL_SCANCODE_8); }
    bool IsPressed_9() { return IsPressed(keyStates,SDL_SCANCODE_9); }
    bool IsPressed_0() { return IsPressed(keyStates,SDL_SCANCODE_0); }
    bool IsPressed_Return() { return IsPressed(keyStates,SDL_SCANCODE_RETURN); }
    bool IsPressed_Escape() { return IsPressed(keyStates,SDL_SCANCODE_ESCAPE); }
    bool IsPressed_Backspace() { return IsPressed(keyStates,SDL_SCANCODE_BACKSPACE); }
    bool IsPressed_Tab() { return IsPressed(keyStates,SDL_SCANCODE_TAB); }
    bool IsPressed_Space() { return IsPressed(keyStates,SDL_SCANCODE_SPACE); }
    bool IsPressed_Minus() { return IsPressed(keyStates,SDL_SCANCODE_MINUS); }
    bool IsPressed_Equals() { return IsPressed(keyStates,SDL_SCANCODE_EQUALS); }
    bool IsPressed_Leftbracket() { return IsPressed(keyStates,SDL_SCANCODE_LEFTBRACKET); }
    bool IsPressed_Rightbracket() { return IsPressed(keyStates,SDL_SCANCODE_RIGHTBRACKET); }
    bool IsPressed_Backslash() { return IsPressed(keyStates,SDL_SCANCODE_BACKSLASH); }
    bool IsPressed_Nonushash() { return IsPressed(keyStates,SDL_SCANCODE_NONUSHASH); }
    bool IsPressed_Semicolon() { return IsPressed(keyStates,SDL_SCANCODE_SEMICOLON); }
    bool IsPressed_Apostrophe() { return IsPressed(keyStates,SDL_SCANCODE_APOSTROPHE); }
    bool IsPressed_Grave() { return IsPressed(keyStates,SDL_SCANCODE_GRAVE); }
    bool IsPressed_Comma() { return IsPressed(keyStates,SDL_SCANCODE_COMMA); }
    bool IsPressed_Period() { return IsPressed(keyStates,SDL_SCANCODE_PERIOD); }
    bool IsPressed_Slash() { return IsPressed(keyStates,SDL_SCANCODE_SLASH); }
    bool IsPressed_CapsLock() { return IsPressed(keyStates,SDL_SCANCODE_CAPSLOCK); }
    bool IsPressed_F1() { return IsPressed(keyStates,SDL_SCANCODE_F1); }
    bool IsPressed_F2() { return IsPressed(keyStates,SDL_SCANCODE_F2); }
    bool IsPressed_F3() { return IsPressed(keyStates,SDL_SCANCODE_F3); }
    bool IsPressed_F4() { return IsPressed(keyStates,SDL_SCANCODE_F4); }
    bool IsPressed_F5() { return IsPressed(keyStates,SDL_SCANCODE_F5); }
    bool IsPressed_F6() { return IsPressed(keyStates,SDL_SCANCODE_F6); }
    bool IsPressed_F7() { return IsPressed(keyStates,SDL_SCANCODE_F7); }
    bool IsPressed_F8() { return IsPressed(keyStates,SDL_SCANCODE_F8); }
    bool IsPressed_F9() { return IsPressed(keyStates,SDL_SCANCODE_F9); }
    bool IsPressed_F10() { return IsPressed(keyStates,SDL_SCANCODE_F10); }
    bool IsPressed_F11() { return IsPressed(keyStates,SDL_SCANCODE_F11); }
    bool IsPressed_F12() { return IsPressed(keyStates,SDL_SCANCODE_F12); }
    bool IsPressed_PrintScreen() { return IsPressed(keyStates,SDL_SCANCODE_PRINTSCREEN); }
    bool IsPressed_ScrollLock() { return IsPressed(keyStates,SDL_SCANCODE_SCROLLLOCK); }
    bool IsPressed_Pause() { return IsPressed(keyStates,SDL_SCANCODE_PAUSE); }
    bool IsPressed_Insert() { return IsPressed(keyStates,SDL_SCANCODE_INSERT); }
    bool IsPressed_Home() { return IsPressed(keyStates,SDL_SCANCODE_HOME); }
    bool IsPressed_PageUp() { return IsPressed(keyStates,SDL_SCANCODE_PAGEUP); }
    bool IsPressed_Delete() { return IsPressed(keyStates,SDL_SCANCODE_DELETE); }
    bool IsPressed_End() { return IsPressed(keyStates,SDL_SCANCODE_END); }
    bool IsPressed_PageDown() { return IsPressed(keyStates,SDL_SCANCODE_PAGEDOWN); }
    bool IsPressed_Right() { return IsPressed(keyStates,SDL_SCANCODE_RIGHT); }
    bool IsPressed_Left() { return IsPressed(keyStates,SDL_SCANCODE_LEFT); }
    bool IsPressed_Down() { return IsPressed(keyStates,SDL_SCANCODE_DOWN); }
    bool IsPressed_Up() { return IsPressed(keyStates,SDL_SCANCODE_UP); }
    bool IsPressed_NumLock() { return IsPressed(keyStates,SDL_SCANCODE_NUMLOCKCLEAR); }
    bool IsPressed_Kp_Divide() { return IsPressed(keyStates,SDL_SCANCODE_KP_DIVIDE); }
    bool IsPressed_Kp_Multiply() { return IsPressed(keyStates,SDL_SCANCODE_KP_MULTIPLY); }
    bool IsPressed_Kp_Minus() { return IsPressed(keyStates,SDL_SCANCODE_KP_MINUS); }
    bool IsPressed_Kp_Plus() { return IsPressed(keyStates,SDL_SCANCODE_KP_PLUS); }
    bool IsPressed_Kp_Enter() { return IsPressed(keyStates,SDL_SCANCODE_KP_ENTER); }
    bool IsPressed_Kp_1() { return IsPressed(keyStates,SDL_SCANCODE_KP_1); }
    bool IsPressed_Kp_2() { return IsPressed(keyStates,SDL_SCANCODE_KP_2); }
    bool IsPressed_Kp_3() { return IsPressed(keyStates,SDL_SCANCODE_KP_3); }
    bool IsPressed_Kp_4() { return IsPressed(keyStates,SDL_SCANCODE_KP_4); }
    bool IsPressed_Kp_5() { return IsPressed(keyStates,SDL_SCANCODE_KP_5); }
    bool IsPressed_Kp_6() { return IsPressed(keyStates,SDL_SCANCODE_KP_6); }
    bool IsPressed_Kp_7() { return IsPressed(keyStates,SDL_SCANCODE_KP_7); }
    bool IsPressed_Kp_8() { return IsPressed(keyStates,SDL_SCANCODE_KP_8); }
    bool IsPressed_Kp_9() { return IsPressed(keyStates,SDL_SCANCODE_KP_9); }
    bool IsPressed_Kp_0() { return IsPressed(keyStates,SDL_SCANCODE_KP_0); }
    bool IsPressed_Kp_Period() { return IsPressed(keyStates,SDL_SCANCODE_KP_PERIOD); }
    bool IsPressed_RBackSlash() { return IsPressed(keyStates,SDL_SCANCODE_NONUSBACKSLASH); }
    bool IsPressed_Application() { return IsPressed(keyStates,SDL_SCANCODE_APPLICATION); }
    bool IsPressed_Power() { return IsPressed(keyStates,SDL_SCANCODE_POWER); }
    bool IsPressed_Kp_Equals() { return IsPressed(keyStates,SDL_SCANCODE_KP_EQUALS); }
    bool IsPressed_Execute() { return IsPressed(keyStates,SDL_SCANCODE_EXECUTE); }
    bool IsPressed_Help() { return IsPressed(keyStates,SDL_SCANCODE_HELP); }
    bool IsPressed_Menu() { return IsPressed(keyStates,SDL_SCANCODE_MENU); }
    bool IsPressed_Select() { return IsPressed(keyStates,SDL_SCANCODE_SELECT); }
    bool IsPressed_Stop() { return IsPressed(keyStates,SDL_SCANCODE_STOP); }
    bool IsPressed_Again() { return IsPressed(keyStates,SDL_SCANCODE_AGAIN); }
    bool IsPressed_Undo() { return IsPressed(keyStates,SDL_SCANCODE_UNDO); }
    bool IsPressed_Cut() { return IsPressed(keyStates,SDL_SCANCODE_CUT); }
    bool IsPressed_Copy() { return IsPressed(keyStates,SDL_SCANCODE_COPY); }
    bool IsPressed_Paste() { return IsPressed(keyStates,SDL_SCANCODE_PASTE); }
    bool IsPressed_Find() { return IsPressed(keyStates,SDL_SCANCODE_FIND); }
    bool IsPressed_Mute() { return IsPressed(keyStates,SDL_SCANCODE_MUTE); }
    bool IsPressed_VolumeUp() { return IsPressed(keyStates,SDL_SCANCODE_VOLUMEUP); }
    bool IsPressed_VolumeDown() { return IsPressed(keyStates,SDL_SCANCODE_VOLUMEDOWN); }
    bool IsPressed_LCtrl() { return IsPressed(keyStates,SDL_SCANCODE_LCTRL); }
    bool IsPressed_LShift() { return IsPressed(keyStates,SDL_SCANCODE_LSHIFT); }
    bool IsPressed_LAlt() { return IsPressed(keyStates,SDL_SCANCODE_LALT); }
    bool IsPressed_LGui() { return IsPressed(keyStates,SDL_SCANCODE_LGUI); }
    bool IsPressed_RCtrl() { return IsPressed(keyStates,SDL_SCANCODE_RCTRL); }
    bool IsPressed_RShift() { return IsPressed(keyStates,SDL_SCANCODE_RSHIFT); }
    bool IsPressed_RAlt() { return IsPressed(keyStates,SDL_SCANCODE_RALT); }
    bool IsPressed_RGui() { return IsPressed(keyStates,SDL_SCANCODE_RGUI); }

    // KEYBOARD RELEASED
    bool IsReleased_A() { return IsReleased(keyStates,SDL_SCANCODE_A); }
    bool IsReleased_B() { return IsReleased(keyStates,SDL_SCANCODE_B); }
    bool IsReleased_C() { return IsReleased(keyStates,SDL_SCANCODE_C); }
    bool IsReleased_D() { return IsReleased(keyStates,SDL_SCANCODE_D); }
    bool IsReleased_E() { return IsReleased(keyStates,SDL_SCANCODE_E); }
    bool IsReleased_F() { return IsReleased(keyStates,SDL_SCANCODE_F); }
    bool IsReleased_G() { return IsReleased(keyStates,SDL_SCANCODE_G); }
    bool IsReleased_H() { return IsReleased(keyStates,SDL_SCANCODE_H); }
    bool IsReleased_I() { return IsReleased(keyStates,SDL_SCANCODE_I); }
    bool IsReleased_J() { return IsReleased(keyStates,SDL_SCANCODE_J); }
    bool IsReleased_K() { return IsReleased(keyStates,SDL_SCANCODE_K); }
    bool IsReleased_L() { return IsReleased(keyStates,SDL_SCANCODE_L); }
    bool IsReleased_M() { return IsReleased(keyStates,SDL_SCANCODE_M); }
    bool IsReleased_N() { return IsReleased(keyStates,SDL_SCANCODE_N); }
    bool IsReleased_O() { return IsReleased(keyStates,SDL_SCANCODE_O); }
    bool IsReleased_P() { return IsReleased(keyStates,SDL_SCANCODE_P); }
    bool IsReleased_Q() { return IsReleased(keyStates,SDL_SCANCODE_Q); }
    bool IsReleased_R() { return IsReleased(keyStates,SDL_SCANCODE_R); }
    bool IsReleased_S() { return IsReleased(keyStates,SDL_SCANCODE_S); }
    bool IsReleased_T() { return IsReleased(keyStates,SDL_SCANCODE_T); }
    bool IsReleased_U() { return IsReleased(keyStates,SDL_SCANCODE_U); }
    bool IsReleased_V() { return IsReleased(keyStates,SDL_SCANCODE_V); }
    bool IsReleased_W() { return IsReleased(keyStates,SDL_SCANCODE_W); }
    bool IsReleased_X() { return IsReleased(keyStates,SDL_SCANCODE_X); }
    bool IsReleased_Y() { return IsReleased(keyStates,SDL_SCANCODE_Y); }
    bool IsReleased_Z() { return IsReleased(keyStates,SDL_SCANCODE_Z); }
    bool IsReleased_1() { return IsReleased(keyStates,SDL_SCANCODE_1); }
    bool IsReleased_2() { return IsReleased(keyStates,SDL_SCANCODE_2); }
    bool IsReleased_3() { return IsReleased(keyStates,SDL_SCANCODE_3); }
    bool IsReleased_4() { return IsReleased(keyStates,SDL_SCANCODE_4); }
    bool IsReleased_5() { return IsReleased(keyStates,SDL_SCANCODE_5); }
    bool IsReleased_6() { return IsReleased(keyStates,SDL_SCANCODE_6); }
    bool IsReleased_7() { return IsReleased(keyStates,SDL_SCANCODE_7); }
    bool IsReleased_8() { return IsReleased(keyStates,SDL_SCANCODE_8); }
    bool IsReleased_9() { return IsReleased(keyStates,SDL_SCANCODE_9); }
    bool IsReleased_0() { return IsReleased(keyStates,SDL_SCANCODE_0); }
    bool IsReleased_Return() { return IsReleased(keyStates,SDL_SCANCODE_RETURN); }
    bool IsReleased_Escape() { return IsReleased(keyStates,SDL_SCANCODE_ESCAPE); }
    bool IsReleased_Backspace() { return IsReleased(keyStates,SDL_SCANCODE_BACKSPACE); }
    bool IsReleased_Tab() { return IsReleased(keyStates,SDL_SCANCODE_TAB); }
    bool IsReleased_Space() { return IsReleased(keyStates,SDL_SCANCODE_SPACE); }
    bool IsReleased_Minus() { return IsReleased(keyStates,SDL_SCANCODE_MINUS); }
    bool IsReleased_Equals() { return IsReleased(keyStates,SDL_SCANCODE_EQUALS); }
    bool IsReleased_Leftbracket() { return IsReleased(keyStates,SDL_SCANCODE_LEFTBRACKET); }
    bool IsReleased_Rightbracket() { return IsReleased(keyStates,SDL_SCANCODE_RIGHTBRACKET); }
    bool IsReleased_Backslash() { return IsReleased(keyStates,SDL_SCANCODE_BACKSLASH); }
    bool IsReleased_Nonushash() { return IsReleased(keyStates,SDL_SCANCODE_NONUSHASH); }
    bool IsReleased_Semicolon() { return IsReleased(keyStates,SDL_SCANCODE_SEMICOLON); }
    bool IsReleased_Apostrophe() { return IsReleased(keyStates,SDL_SCANCODE_APOSTROPHE); }
    bool IsReleased_Grave() { return IsReleased(keyStates,SDL_SCANCODE_GRAVE); }
    bool IsReleased_Comma() { return IsReleased(keyStates,SDL_SCANCODE_COMMA); }
    bool IsReleased_Period() { return IsReleased(keyStates,SDL_SCANCODE_PERIOD); }
    bool IsReleased_Slash() { return IsReleased(keyStates,SDL_SCANCODE_SLASH); }
    bool IsReleased_CapsLock() { return IsReleased(keyStates,SDL_SCANCODE_CAPSLOCK); }
    bool IsReleased_F1() { return IsReleased(keyStates,SDL_SCANCODE_F1); }
    bool IsReleased_F2() { return IsReleased(keyStates,SDL_SCANCODE_F2); }
    bool IsReleased_F3() { return IsReleased(keyStates,SDL_SCANCODE_F3); }
    bool IsReleased_F4() { return IsReleased(keyStates,SDL_SCANCODE_F4); }
    bool IsReleased_F5() { return IsReleased(keyStates,SDL_SCANCODE_F5); }
    bool IsReleased_F6() { return IsReleased(keyStates,SDL_SCANCODE_F6); }
    bool IsReleased_F7() { return IsReleased(keyStates,SDL_SCANCODE_F7); }
    bool IsReleased_F8() { return IsReleased(keyStates,SDL_SCANCODE_F8); }
    bool IsReleased_F9() { return IsReleased(keyStates,SDL_SCANCODE_F9); }
    bool IsReleased_F10() { return IsReleased(keyStates,SDL_SCANCODE_F10); }
    bool IsReleased_F11() { return IsReleased(keyStates,SDL_SCANCODE_F11); }
    bool IsReleased_F12() { return IsReleased(keyStates,SDL_SCANCODE_F12); }
    bool IsReleased_PrintScreen() { return IsReleased(keyStates,SDL_SCANCODE_PRINTSCREEN); }
    bool IsReleased_ScrollLock() { return IsReleased(keyStates,SDL_SCANCODE_SCROLLLOCK); }
    bool IsReleased_Pause() { return IsReleased(keyStates,SDL_SCANCODE_PAUSE); }
    bool IsReleased_Insert() { return IsReleased(keyStates,SDL_SCANCODE_INSERT); }
    bool IsReleased_Home() { return IsReleased(keyStates,SDL_SCANCODE_HOME); }
    bool IsReleased_PageUp() { return IsReleased(keyStates,SDL_SCANCODE_PAGEUP); }
    bool IsReleased_Delete() { return IsReleased(keyStates,SDL_SCANCODE_DELETE); }
    bool IsReleased_End() { return IsReleased(keyStates,SDL_SCANCODE_END); }
    bool IsReleased_PageDown() { return IsReleased(keyStates,SDL_SCANCODE_PAGEDOWN); }
    bool IsReleased_Right() { return IsReleased(keyStates,SDL_SCANCODE_RIGHT); }
    bool IsReleased_Left() { return IsReleased(keyStates,SDL_SCANCODE_LEFT); }
    bool IsReleased_Down() { return IsReleased(keyStates,SDL_SCANCODE_DOWN); }
    bool IsReleased_Up() { return IsReleased(keyStates,SDL_SCANCODE_UP); }
    bool IsReleased_NumLock() { return IsReleased(keyStates,SDL_SCANCODE_NUMLOCKCLEAR); }
    bool IsReleased_Kp_Divide() { return IsReleased(keyStates,SDL_SCANCODE_KP_DIVIDE); }
    bool IsReleased_Kp_Multiply() { return IsReleased(keyStates,SDL_SCANCODE_KP_MULTIPLY); }
    bool IsReleased_Kp_Minus() { return IsReleased(keyStates,SDL_SCANCODE_KP_MINUS); }
    bool IsReleased_Kp_Plus() { return IsReleased(keyStates,SDL_SCANCODE_KP_PLUS); }
    bool IsReleased_Kp_Enter() { return IsReleased(keyStates,SDL_SCANCODE_KP_ENTER); }
    bool IsReleased_Kp_1() { return IsReleased(keyStates,SDL_SCANCODE_KP_1); }
    bool IsReleased_Kp_2() { return IsReleased(keyStates,SDL_SCANCODE_KP_2); }
    bool IsReleased_Kp_3() { return IsReleased(keyStates,SDL_SCANCODE_KP_3); }
    bool IsReleased_Kp_4() { return IsReleased(keyStates,SDL_SCANCODE_KP_4); }
    bool IsReleased_Kp_5() { return IsReleased(keyStates,SDL_SCANCODE_KP_5); }
    bool IsReleased_Kp_6() { return IsReleased(keyStates,SDL_SCANCODE_KP_6); }
    bool IsReleased_Kp_7() { return IsReleased(keyStates,SDL_SCANCODE_KP_7); }
    bool IsReleased_Kp_8() { return IsReleased(keyStates,SDL_SCANCODE_KP_8); }
    bool IsReleased_Kp_9() { return IsReleased(keyStates,SDL_SCANCODE_KP_9); }
    bool IsReleased_Kp_0() { return IsReleased(keyStates,SDL_SCANCODE_KP_0); }
    bool IsReleased_Kp_Period() { return IsReleased(keyStates,SDL_SCANCODE_KP_PERIOD); }
    bool IsReleased_RBackSlash() { return IsReleased(keyStates,SDL_SCANCODE_NONUSBACKSLASH); }
    bool IsReleased_Application() { return IsReleased(keyStates,SDL_SCANCODE_APPLICATION); }
    bool IsReleased_Power() { return IsReleased(keyStates,SDL_SCANCODE_POWER); }
    bool IsReleased_Kp_Equals() { return IsReleased(keyStates,SDL_SCANCODE_KP_EQUALS); }
    bool IsReleased_Execute() { return IsReleased(keyStates,SDL_SCANCODE_EXECUTE); }
    bool IsReleased_Help() { return IsReleased(keyStates,SDL_SCANCODE_HELP); }
    bool IsReleased_Menu() { return IsReleased(keyStates,SDL_SCANCODE_MENU); }
    bool IsReleased_Select() { return IsReleased(keyStates,SDL_SCANCODE_SELECT); }
    bool IsReleased_Stop() { return IsReleased(keyStates,SDL_SCANCODE_STOP); }
    bool IsReleased_Again() { return IsReleased(keyStates,SDL_SCANCODE_AGAIN); }
    bool IsReleased_Undo() { return IsReleased(keyStates,SDL_SCANCODE_UNDO); }
    bool IsReleased_Cut() { return IsReleased(keyStates,SDL_SCANCODE_CUT); }
    bool IsReleased_Copy() { return IsReleased(keyStates,SDL_SCANCODE_COPY); }
    bool IsReleased_Paste() { return IsReleased(keyStates,SDL_SCANCODE_PASTE); }
    bool IsReleased_Find() { return IsReleased(keyStates,SDL_SCANCODE_FIND); }
    bool IsReleased_Mute() { return IsReleased(keyStates,SDL_SCANCODE_MUTE); }
    bool IsReleased_VolumeUp() { return IsReleased(keyStates,SDL_SCANCODE_VOLUMEUP); }
    bool IsReleased_VolumeDown() { return IsReleased(keyStates,SDL_SCANCODE_VOLUMEDOWN); }
    bool IsReleased_LCtrl() { return IsReleased(keyStates,SDL_SCANCODE_LCTRL); }
    bool IsReleased_LShift() { return IsReleased(keyStates,SDL_SCANCODE_LSHIFT); }
    bool IsReleased_LAlt() { return IsReleased(keyStates,SDL_SCANCODE_LALT); }
    bool IsReleased_LGui() { return IsReleased(keyStates,SDL_SCANCODE_LGUI); }
    bool IsReleased_RCtrl() { return IsReleased(keyStates,SDL_SCANCODE_RCTRL); }
    bool IsReleased_RShift() { return IsReleased(keyStates,SDL_SCANCODE_RSHIFT); }
    bool IsReleased_RAlt() { return IsReleased(keyStates,SDL_SCANCODE_RALT); }
    bool IsReleased_RGui() { return IsReleased(keyStates,SDL_SCANCODE_RGUI); }

    // KEYBOARD Down
    bool IsDown_A() { return IsDown(keyStates,SDL_SCANCODE_A); }
    bool IsDown_B() { return IsDown(keyStates,SDL_SCANCODE_B); }
    bool IsDown_C() { return IsDown(keyStates,SDL_SCANCODE_C); }
    bool IsDown_D() { return IsDown(keyStates,SDL_SCANCODE_D); }
    bool IsDown_E() { return IsDown(keyStates,SDL_SCANCODE_E); }
    bool IsDown_F() { return IsDown(keyStates,SDL_SCANCODE_F); }
    bool IsDown_G() { return IsDown(keyStates,SDL_SCANCODE_G); }
    bool IsDown_H() { return IsDown(keyStates,SDL_SCANCODE_H); }
    bool IsDown_I() { return IsDown(keyStates,SDL_SCANCODE_I); }
    bool IsDown_J() { return IsDown(keyStates,SDL_SCANCODE_J); }
    bool IsDown_K() { return IsDown(keyStates,SDL_SCANCODE_K); }
    bool IsDown_L() { return IsDown(keyStates,SDL_SCANCODE_L); }
    bool IsDown_M() { return IsDown(keyStates,SDL_SCANCODE_M); }
    bool IsDown_N() { return IsDown(keyStates,SDL_SCANCODE_N); }
    bool IsDown_O() { return IsDown(keyStates,SDL_SCANCODE_O); }
    bool IsDown_P() { return IsDown(keyStates,SDL_SCANCODE_P); }
    bool IsDown_Q() { return IsDown(keyStates,SDL_SCANCODE_Q); }
    bool IsDown_R() { return IsDown(keyStates,SDL_SCANCODE_R); }
    bool IsDown_S() { return IsDown(keyStates,SDL_SCANCODE_S); }
    bool IsDown_T() { return IsDown(keyStates,SDL_SCANCODE_T); }
    bool IsDown_U() { return IsDown(keyStates,SDL_SCANCODE_U); }
    bool IsDown_V() { return IsDown(keyStates,SDL_SCANCODE_V); }
    bool IsDown_W() { return IsDown(keyStates,SDL_SCANCODE_W); }
    bool IsDown_X() { return IsDown(keyStates,SDL_SCANCODE_X); }
    bool IsDown_Y() { return IsDown(keyStates,SDL_SCANCODE_Y); }
    bool IsDown_Z() { return IsDown(keyStates,SDL_SCANCODE_Z); }
    bool IsDown_1() { return IsDown(keyStates,SDL_SCANCODE_1); }
    bool IsDown_2() { return IsDown(keyStates,SDL_SCANCODE_2); }
    bool IsDown_3() { return IsDown(keyStates,SDL_SCANCODE_3); }
    bool IsDown_4() { return IsDown(keyStates,SDL_SCANCODE_4); }
    bool IsDown_5() { return IsDown(keyStates,SDL_SCANCODE_5); }
    bool IsDown_6() { return IsDown(keyStates,SDL_SCANCODE_6); }
    bool IsDown_7() { return IsDown(keyStates,SDL_SCANCODE_7); }
    bool IsDown_8() { return IsDown(keyStates,SDL_SCANCODE_8); }
    bool IsDown_9() { return IsDown(keyStates,SDL_SCANCODE_9); }
    bool IsDown_0() { return IsDown(keyStates,SDL_SCANCODE_0); }
    bool IsDown_Return() { return IsDown(keyStates,SDL_SCANCODE_RETURN); }
    bool IsDown_Escape() { return IsDown(keyStates,SDL_SCANCODE_ESCAPE); }
    bool IsDown_Backspace() { return IsDown(keyStates,SDL_SCANCODE_BACKSPACE); }
    bool IsDown_Tab() { return IsDown(keyStates,SDL_SCANCODE_TAB); }
    bool IsDown_Space() { return IsDown(keyStates,SDL_SCANCODE_SPACE); }
    bool IsDown_Minus() { return IsDown(keyStates,SDL_SCANCODE_MINUS); }
    bool IsDown_Equals() { return IsDown(keyStates,SDL_SCANCODE_EQUALS); }
    bool IsDown_Leftbracket() { return IsDown(keyStates,SDL_SCANCODE_LEFTBRACKET); }
    bool IsDown_Rightbracket() { return IsDown(keyStates,SDL_SCANCODE_RIGHTBRACKET); }
    bool IsDown_Backslash() { return IsDown(keyStates,SDL_SCANCODE_BACKSLASH); }
    bool IsDown_Nonushash() { return IsDown(keyStates,SDL_SCANCODE_NONUSHASH); }
    bool IsDown_Semicolon() { return IsDown(keyStates,SDL_SCANCODE_SEMICOLON); }
    bool IsDown_Apostrophe() { return IsDown(keyStates,SDL_SCANCODE_APOSTROPHE); }
    bool IsDown_Grave() { return IsDown(keyStates,SDL_SCANCODE_GRAVE); }
    bool IsDown_Comma() { return IsDown(keyStates,SDL_SCANCODE_COMMA); }
    bool IsDown_Period() { return IsDown(keyStates,SDL_SCANCODE_PERIOD); }
    bool IsDown_Slash() { return IsDown(keyStates,SDL_SCANCODE_SLASH); }
    bool IsDown_CapsLock() { return IsDown(keyStates,SDL_SCANCODE_CAPSLOCK); }
    bool IsDown_F1() { return IsDown(keyStates,SDL_SCANCODE_F1); }
    bool IsDown_F2() { return IsDown(keyStates,SDL_SCANCODE_F2); }
    bool IsDown_F3() { return IsDown(keyStates,SDL_SCANCODE_F3); }
    bool IsDown_F4() { return IsDown(keyStates,SDL_SCANCODE_F4); }
    bool IsDown_F5() { return IsDown(keyStates,SDL_SCANCODE_F5); }
    bool IsDown_F6() { return IsDown(keyStates,SDL_SCANCODE_F6); }
    bool IsDown_F7() { return IsDown(keyStates,SDL_SCANCODE_F7); }
    bool IsDown_F8() { return IsDown(keyStates,SDL_SCANCODE_F8); }
    bool IsDown_F9() { return IsDown(keyStates,SDL_SCANCODE_F9); }
    bool IsDown_F10() { return IsDown(keyStates,SDL_SCANCODE_F10); }
    bool IsDown_F11() { return IsDown(keyStates,SDL_SCANCODE_F11); }
    bool IsDown_F12() { return IsDown(keyStates,SDL_SCANCODE_F12); }
    bool IsDown_PrintScreen() { return IsDown(keyStates,SDL_SCANCODE_PRINTSCREEN); }
    bool IsDown_ScrollLock() { return IsDown(keyStates,SDL_SCANCODE_SCROLLLOCK); }
    bool IsDown_Pause() { return IsDown(keyStates,SDL_SCANCODE_PAUSE); }
    bool IsDown_Insert() { return IsDown(keyStates,SDL_SCANCODE_INSERT); }
    bool IsDown_Home() { return IsDown(keyStates,SDL_SCANCODE_HOME); }
    bool IsDown_PageUp() { return IsDown(keyStates,SDL_SCANCODE_PAGEUP); }
    bool IsDown_Delete() { return IsDown(keyStates,SDL_SCANCODE_DELETE); }
    bool IsDown_End() { return IsDown(keyStates,SDL_SCANCODE_END); }
    bool IsDown_PageDown() { return IsDown(keyStates,SDL_SCANCODE_PAGEDOWN); }
    bool IsDown_Right() { return IsDown(keyStates,SDL_SCANCODE_RIGHT); }
    bool IsDown_Left() { return IsDown(keyStates,SDL_SCANCODE_LEFT); }
    bool IsDown_Down() { return IsDown(keyStates,SDL_SCANCODE_DOWN); }
    bool IsDown_Up() { return IsDown(keyStates,SDL_SCANCODE_UP); }
    bool IsDown_NumLock() { return IsDown(keyStates,SDL_SCANCODE_NUMLOCKCLEAR); }
    bool IsDown_Kp_Divide() { return IsDown(keyStates,SDL_SCANCODE_KP_DIVIDE); }
    bool IsDown_Kp_Multiply() { return IsDown(keyStates,SDL_SCANCODE_KP_MULTIPLY); }
    bool IsDown_Kp_Minus() { return IsDown(keyStates,SDL_SCANCODE_KP_MINUS); }
    bool IsDown_Kp_Plus() { return IsDown(keyStates,SDL_SCANCODE_KP_PLUS); }
    bool IsDown_Kp_Enter() { return IsDown(keyStates,SDL_SCANCODE_KP_ENTER); }
    bool IsDown_Kp_1() { return IsDown(keyStates,SDL_SCANCODE_KP_1); }
    bool IsDown_Kp_2() { return IsDown(keyStates,SDL_SCANCODE_KP_2); }
    bool IsDown_Kp_3() { return IsDown(keyStates,SDL_SCANCODE_KP_3); }
    bool IsDown_Kp_4() { return IsDown(keyStates,SDL_SCANCODE_KP_4); }
    bool IsDown_Kp_5() { return IsDown(keyStates,SDL_SCANCODE_KP_5); }
    bool IsDown_Kp_6() { return IsDown(keyStates,SDL_SCANCODE_KP_6); }
    bool IsDown_Kp_7() { return IsDown(keyStates,SDL_SCANCODE_KP_7); }
    bool IsDown_Kp_8() { return IsDown(keyStates,SDL_SCANCODE_KP_8); }
    bool IsDown_Kp_9() { return IsDown(keyStates,SDL_SCANCODE_KP_9); }
    bool IsDown_Kp_0() { return IsDown(keyStates,SDL_SCANCODE_KP_0); }
    bool IsDown_Kp_Period() { return IsDown(keyStates,SDL_SCANCODE_KP_PERIOD); }
    bool IsDown_RBackSlash() { return IsDown(keyStates,SDL_SCANCODE_NONUSBACKSLASH); }
    bool IsDown_Application() { return IsDown(keyStates,SDL_SCANCODE_APPLICATION); }
    bool IsDown_Power() { return IsDown(keyStates,SDL_SCANCODE_POWER); }
    bool IsDown_Kp_Equals() { return IsDown(keyStates,SDL_SCANCODE_KP_EQUALS); }
    bool IsDown_Execute() { return IsDown(keyStates,SDL_SCANCODE_EXECUTE); }
    bool IsDown_Help() { return IsDown(keyStates,SDL_SCANCODE_HELP); }
    bool IsDown_Menu() { return IsDown(keyStates,SDL_SCANCODE_MENU); }
    bool IsDown_Select() { return IsDown(keyStates,SDL_SCANCODE_SELECT); }
    bool IsDown_Stop() { return IsDown(keyStates,SDL_SCANCODE_STOP); }
    bool IsDown_Again() { return IsDown(keyStates,SDL_SCANCODE_AGAIN); }
    bool IsDown_Undo() { return IsDown(keyStates,SDL_SCANCODE_UNDO); }
    bool IsDown_Cut() { return IsDown(keyStates,SDL_SCANCODE_CUT); }
    bool IsDown_Copy() { return IsDown(keyStates,SDL_SCANCODE_COPY); }
    bool IsDown_Paste() { return IsDown(keyStates,SDL_SCANCODE_PASTE); }
    bool IsDown_Find() { return IsDown(keyStates,SDL_SCANCODE_FIND); }
    bool IsDown_Mute() { return IsDown(keyStates,SDL_SCANCODE_MUTE); }
    bool IsDown_VolumeUp() { return IsDown(keyStates,SDL_SCANCODE_VOLUMEUP); }
    bool IsDown_VolumeDown() { return IsDown(keyStates,SDL_SCANCODE_VOLUMEDOWN); }
    bool IsDown_LCtrl() { return IsDown(keyStates,SDL_SCANCODE_LCTRL); }
    bool IsDown_LShift() { return IsDown(keyStates,SDL_SCANCODE_LSHIFT); }
    bool IsDown_LAlt() { return IsDown(keyStates,SDL_SCANCODE_LALT); }
    bool IsDown_LGui() { return IsDown(keyStates,SDL_SCANCODE_LGUI); }
    bool IsDown_RCtrl() { return IsDown(keyStates,SDL_SCANCODE_RCTRL); }
    bool IsDown_RShift() { return IsDown(keyStates,SDL_SCANCODE_RSHIFT); }
    bool IsDown_RAlt() { return IsDown(keyStates,SDL_SCANCODE_RALT); }
    bool IsDown_RGui() { return IsDown(keyStates,SDL_SCANCODE_RGUI); }

    // KEYBOARD Down
    bool IsUp_A() { return !IsUp(keyStates,SDL_SCANCODE_A); }
    bool IsUp_B() { return !IsUp(keyStates,SDL_SCANCODE_B); }
    bool IsUp_C() { return !IsUp(keyStates,SDL_SCANCODE_C); }
    bool IsUp_D() { return !IsUp(keyStates,SDL_SCANCODE_D); }
    bool IsUp_E() { return !IsUp(keyStates,SDL_SCANCODE_E); }
    bool IsUp_F() { return !IsUp(keyStates,SDL_SCANCODE_F); }
    bool IsUp_G() { return !IsUp(keyStates,SDL_SCANCODE_G); }
    bool IsUp_H() { return !IsUp(keyStates,SDL_SCANCODE_H); }
    bool IsUp_I() { return !IsUp(keyStates,SDL_SCANCODE_I); }
    bool IsUp_J() { return !IsUp(keyStates,SDL_SCANCODE_J); }
    bool IsUp_K() { return !IsUp(keyStates,SDL_SCANCODE_K); }
    bool IsUp_L() { return !IsUp(keyStates,SDL_SCANCODE_L); }
    bool IsUp_M() { return !IsUp(keyStates,SDL_SCANCODE_M); }
    bool IsUp_N() { return !IsUp(keyStates,SDL_SCANCODE_N); }
    bool IsUp_O() { return !IsUp(keyStates,SDL_SCANCODE_O); }
    bool IsUp_P() { return !IsUp(keyStates,SDL_SCANCODE_P); }
    bool IsUp_Q() { return !IsUp(keyStates,SDL_SCANCODE_Q); }
    bool IsUp_R() { return !IsUp(keyStates,SDL_SCANCODE_R); }
    bool IsUp_S() { return !IsUp(keyStates,SDL_SCANCODE_S); }
    bool IsUp_T() { return !IsUp(keyStates,SDL_SCANCODE_T); }
    bool IsUp_U() { return !IsUp(keyStates,SDL_SCANCODE_U); }
    bool IsUp_V() { return !IsUp(keyStates,SDL_SCANCODE_V); }
    bool IsUp_W() { return !IsUp(keyStates,SDL_SCANCODE_W); }
    bool IsUp_X() { return !IsUp(keyStates,SDL_SCANCODE_X); }
    bool IsUp_Y() { return !IsUp(keyStates,SDL_SCANCODE_Y); }
    bool IsUp_Z() { return !IsUp(keyStates,SDL_SCANCODE_Z); }
    bool IsUp_1() { return !IsUp(keyStates,SDL_SCANCODE_1); }
    bool IsUp_2() { return !IsUp(keyStates,SDL_SCANCODE_2); }
    bool IsUp_3() { return !IsUp(keyStates,SDL_SCANCODE_3); }
    bool IsUp_4() { return !IsUp(keyStates,SDL_SCANCODE_4); }
    bool IsUp_5() { return !IsUp(keyStates,SDL_SCANCODE_5); }
    bool IsUp_6() { return !IsUp(keyStates,SDL_SCANCODE_6); }
    bool IsUp_7() { return !IsUp(keyStates,SDL_SCANCODE_7); }
    bool IsUp_8() { return !IsUp(keyStates,SDL_SCANCODE_8); }
    bool IsUp_9() { return !IsUp(keyStates,SDL_SCANCODE_9); }
    bool IsUp_0() { return !IsUp(keyStates,SDL_SCANCODE_0); }
    bool IsUp_Return() { return !IsUp(keyStates,SDL_SCANCODE_RETURN); }
    bool IsUp_Escape() { return !IsUp(keyStates,SDL_SCANCODE_ESCAPE); }
    bool IsUp_Backspace() { return !IsUp(keyStates,SDL_SCANCODE_BACKSPACE); }
    bool IsUp_Tab() { return !IsUp(keyStates,SDL_SCANCODE_TAB); }
    bool IsUp_Space() { return !IsUp(keyStates,SDL_SCANCODE_SPACE); }
    bool IsUp_Minus() { return !IsUp(keyStates,SDL_SCANCODE_MINUS); }
    bool IsUp_Equals() { return !IsUp(keyStates,SDL_SCANCODE_EQUALS); }
    bool IsUp_Leftbracket() { return !IsUp(keyStates,SDL_SCANCODE_LEFTBRACKET); }
    bool IsUp_Rightbracket() { return !IsUp(keyStates,SDL_SCANCODE_RIGHTBRACKET); }
    bool IsUp_Backslash() { return !IsUp(keyStates,SDL_SCANCODE_BACKSLASH); }
    bool IsUp_Nonushash() { return !IsUp(keyStates,SDL_SCANCODE_NONUSHASH); }
    bool IsUp_Semicolon() { return !IsUp(keyStates,SDL_SCANCODE_SEMICOLON); }
    bool IsUp_Apostrophe() { return !IsUp(keyStates,SDL_SCANCODE_APOSTROPHE); }
    bool IsUp_Grave() { return !IsUp(keyStates,SDL_SCANCODE_GRAVE); }
    bool IsUp_Comma() { return !IsUp(keyStates,SDL_SCANCODE_COMMA); }
    bool IsUp_Period() { return !IsUp(keyStates,SDL_SCANCODE_PERIOD); }
    bool IsUp_Slash() { return !IsUp(keyStates,SDL_SCANCODE_SLASH); }
    bool IsUp_CapsLock() { return !IsUp(keyStates,SDL_SCANCODE_CAPSLOCK); }
    bool IsUp_F1() { return !IsUp(keyStates,SDL_SCANCODE_F1); }
    bool IsUp_F2() { return !IsUp(keyStates,SDL_SCANCODE_F2); }
    bool IsUp_F3() { return !IsUp(keyStates,SDL_SCANCODE_F3); }
    bool IsUp_F4() { return !IsUp(keyStates,SDL_SCANCODE_F4); }
    bool IsUp_F5() { return !IsUp(keyStates,SDL_SCANCODE_F5); }
    bool IsUp_F6() { return !IsUp(keyStates,SDL_SCANCODE_F6); }
    bool IsUp_F7() { return !IsUp(keyStates,SDL_SCANCODE_F7); }
    bool IsUp_F8() { return !IsUp(keyStates,SDL_SCANCODE_F8); }
    bool IsUp_F9() { return !IsUp(keyStates,SDL_SCANCODE_F9); }
    bool IsUp_F10() { return !IsUp(keyStates,SDL_SCANCODE_F10); }
    bool IsUp_F11() { return !IsUp(keyStates,SDL_SCANCODE_F11); }
    bool IsUp_F12() { return !IsUp(keyStates,SDL_SCANCODE_F12); }
    bool IsUp_PrintScreen() { return !IsUp(keyStates,SDL_SCANCODE_PRINTSCREEN); }
    bool IsUp_ScrollLock() { return !IsUp(keyStates,SDL_SCANCODE_SCROLLLOCK); }
    bool IsUp_Pause() { return !IsUp(keyStates,SDL_SCANCODE_PAUSE); }
    bool IsUp_Insert() { return !IsUp(keyStates,SDL_SCANCODE_INSERT); }
    bool IsUp_Home() { return !IsUp(keyStates,SDL_SCANCODE_HOME); }
    bool IsUp_PageUp() { return !IsUp(keyStates,SDL_SCANCODE_PAGEUP); }
    bool IsUp_Delete() { return !IsUp(keyStates,SDL_SCANCODE_DELETE); }
    bool IsUp_End() { return !IsUp(keyStates,SDL_SCANCODE_END); }
    bool IsUp_PageDown() { return !IsUp(keyStates,SDL_SCANCODE_PAGEDOWN); }
    bool IsUp_Right() { return !IsUp(keyStates,SDL_SCANCODE_RIGHT); }
    bool IsUp_Left() { return !IsUp(keyStates,SDL_SCANCODE_LEFT); }
    bool IsUp_Down() { return !IsUp(keyStates,SDL_SCANCODE_DOWN); }
    bool IsUp_Up() { return !IsUp(keyStates,SDL_SCANCODE_UP); }
    bool IsUp_NumLock() { return !IsUp(keyStates,SDL_SCANCODE_NUMLOCKCLEAR); }
    bool IsUp_Kp_Divide() { return !IsUp(keyStates,SDL_SCANCODE_KP_DIVIDE); }
    bool IsUp_Kp_Multiply() { return !IsUp(keyStates,SDL_SCANCODE_KP_MULTIPLY); }
    bool IsUp_Kp_Minus() { return !IsUp(keyStates,SDL_SCANCODE_KP_MINUS); }
    bool IsUp_Kp_Plus() { return !IsUp(keyStates,SDL_SCANCODE_KP_PLUS); }
    bool IsUp_Kp_Enter() { return !IsUp(keyStates,SDL_SCANCODE_KP_ENTER); }
    bool IsUp_Kp_1() { return !IsUp(keyStates,SDL_SCANCODE_KP_1); }
    bool IsUp_Kp_2() { return !IsUp(keyStates,SDL_SCANCODE_KP_2); }
    bool IsUp_Kp_3() { return !IsUp(keyStates,SDL_SCANCODE_KP_3); }
    bool IsUp_Kp_4() { return !IsUp(keyStates,SDL_SCANCODE_KP_4); }
    bool IsUp_Kp_5() { return !IsUp(keyStates,SDL_SCANCODE_KP_5); }
    bool IsUp_Kp_6() { return !IsUp(keyStates,SDL_SCANCODE_KP_6); }
    bool IsUp_Kp_7() { return !IsUp(keyStates,SDL_SCANCODE_KP_7); }
    bool IsUp_Kp_8() { return !IsUp(keyStates,SDL_SCANCODE_KP_8); }
    bool IsUp_Kp_9() { return !IsUp(keyStates,SDL_SCANCODE_KP_9); }
    bool IsUp_Kp_0() { return !IsUp(keyStates,SDL_SCANCODE_KP_0); }
    bool IsUp_Kp_Period() { return !IsUp(keyStates,SDL_SCANCODE_KP_PERIOD); }
    bool IsUp_RBackSlash() { return !IsUp(keyStates,SDL_SCANCODE_NONUSBACKSLASH); }
    bool IsUp_Application() { return !IsUp(keyStates,SDL_SCANCODE_APPLICATION); }
    bool IsUp_Power() { return !IsUp(keyStates,SDL_SCANCODE_POWER); }
    bool IsUp_Kp_Equals() { return !IsUp(keyStates,SDL_SCANCODE_KP_EQUALS); }
    bool IsUp_Execute() { return !IsUp(keyStates,SDL_SCANCODE_EXECUTE); }
    bool IsUp_Help() { return !IsUp(keyStates,SDL_SCANCODE_HELP); }
    bool IsUp_Menu() { return !IsUp(keyStates,SDL_SCANCODE_MENU); }
    bool IsUp_Select() { return !IsUp(keyStates,SDL_SCANCODE_SELECT); }
    bool IsUp_Stop() { return !IsUp(keyStates,SDL_SCANCODE_STOP); }
    bool IsUp_Again() { return !IsUp(keyStates,SDL_SCANCODE_AGAIN); }
    bool IsUp_Undo() { return !IsUp(keyStates,SDL_SCANCODE_UNDO); }
    bool IsUp_Cut() { return !IsUp(keyStates,SDL_SCANCODE_CUT); }
    bool IsUp_Copy() { return !IsUp(keyStates,SDL_SCANCODE_COPY); }
    bool IsUp_Paste() { return !IsUp(keyStates,SDL_SCANCODE_PASTE); }
    bool IsUp_Find() { return !IsUp(keyStates,SDL_SCANCODE_FIND); }
    bool IsUp_Mute() { return !IsUp(keyStates,SDL_SCANCODE_MUTE); }
    bool IsUp_VolumeUp() { return !IsUp(keyStates,SDL_SCANCODE_VOLUMEUP); }
    bool IsUp_VolumeDown() { return !IsUp(keyStates,SDL_SCANCODE_VOLUMEDOWN); }
    bool IsUp_LCtrl() { return !IsUp(keyStates,SDL_SCANCODE_LCTRL); }
    bool IsUp_LShift() { return !IsUp(keyStates,SDL_SCANCODE_LSHIFT); }
    bool IsUp_LAlt() { return !IsUp(keyStates,SDL_SCANCODE_LALT); }
    bool IsUp_LGui() { return !IsUp(keyStates,SDL_SCANCODE_LGUI); }
    bool IsUp_RCtrl() { return !IsUp(keyStates,SDL_SCANCODE_RCTRL); }
    bool IsUp_RShift() { return !IsUp(keyStates,SDL_SCANCODE_RSHIFT); }
    bool IsUp_RAlt() { return !IsUp(keyStates,SDL_SCANCODE_RALT); }
    bool IsUp_RGui() { return !IsUp(keyStates,SDL_SCANCODE_RGUI); }
};